/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ejercicioexamen;

import java.awt.Color;
import static javax.swing.JOptionPane.showMessageDialog;

/**
 *
 * @author SERGIO
 */
public class Ventana extends javax.swing.JFrame {

    /**
     * Creates new form Ventana
     */
    public Ventana() {
        initComponents();
        cambiarColor();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        buttonGroup = new javax.swing.ButtonGroup();
        jPanelTexto = new javax.swing.JPanel();
        jLabelTexto = new javax.swing.JLabel();
        jPanelRadioButtons = new javax.swing.JPanel();
        jRadioButtonFondo = new javax.swing.JRadioButton();
        jRadioButtonTexto = new javax.swing.JRadioButton();
        jPanelSalir = new javax.swing.JPanel();
        jButtonSalir = new javax.swing.JButton();
        jPanelSliders = new javax.swing.JPanel();
        jLabelVerde = new javax.swing.JLabel();
        jLabelRojo1 = new javax.swing.JLabel();
        jLabelAzul = new javax.swing.JLabel();
        jSliderRojo = new javax.swing.JSlider();
        jTextFieldRojo = new javax.swing.JTextField();
        jTextFieldVerde = new javax.swing.JTextField();
        jTextFieldAzul = new javax.swing.JTextField();
        jSliderAzul = new javax.swing.JSlider();
        jSliderVerde = new javax.swing.JSlider();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Cambiar color");
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabelTexto.setBackground(new java.awt.Color(255, 255, 255));
        jLabelTexto.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabelTexto.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelTexto.setText("Informática I");
        jLabelTexto.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED));
        jLabelTexto.setOpaque(true);

        javax.swing.GroupLayout jPanelTextoLayout = new javax.swing.GroupLayout(jPanelTexto);
        jPanelTexto.setLayout(jPanelTextoLayout);
        jPanelTextoLayout.setHorizontalGroup(
            jPanelTextoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelTextoLayout.createSequentialGroup()
                .addComponent(jLabelTexto, javax.swing.GroupLayout.PREFERRED_SIZE, 559, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 14, Short.MAX_VALUE))
        );
        jPanelTextoLayout.setVerticalGroup(
            jPanelTextoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelTextoLayout.createSequentialGroup()
                .addComponent(jLabelTexto, javax.swing.GroupLayout.DEFAULT_SIZE, 94, Short.MAX_VALUE)
                .addContainerGap())
        );

        getContentPane().add(jPanelTexto, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 6, 573, -1));

        jPanelRadioButtons.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED));

        buttonGroup.add(jRadioButtonFondo);
        jRadioButtonFondo.setSelected(true);
        jRadioButtonFondo.setText("Fondo");
        jRadioButtonFondo.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jRadioButtonFondoFocusGained(evt);
            }
        });
        jRadioButtonFondo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonFondoActionPerformed(evt);
            }
        });

        buttonGroup.add(jRadioButtonTexto);
        jRadioButtonTexto.setText("Texto");
        jRadioButtonTexto.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jRadioButtonTextoStateChanged(evt);
            }
        });
        jRadioButtonTexto.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jRadioButtonTextoFocusGained(evt);
            }
        });
        jRadioButtonTexto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonTextoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelRadioButtonsLayout = new javax.swing.GroupLayout(jPanelRadioButtons);
        jPanelRadioButtons.setLayout(jPanelRadioButtonsLayout);
        jPanelRadioButtonsLayout.setHorizontalGroup(
            jPanelRadioButtonsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelRadioButtonsLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jRadioButtonFondo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jRadioButtonTexto)
                .addContainerGap(71, Short.MAX_VALUE))
        );
        jPanelRadioButtonsLayout.setVerticalGroup(
            jPanelRadioButtonsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelRadioButtonsLayout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(jPanelRadioButtonsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRadioButtonFondo)
                    .addComponent(jRadioButtonTexto))
                .addContainerGap(35, Short.MAX_VALUE))
        );

        getContentPane().add(jPanelRadioButtons, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 124, -1, -1));

        jButtonSalir.setText("Salir");
        jButtonSalir.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonSalir.setPreferredSize(new java.awt.Dimension(215, 97));
        jButtonSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSalirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelSalirLayout = new javax.swing.GroupLayout(jPanelSalir);
        jPanelSalir.setLayout(jPanelSalirLayout);
        jPanelSalirLayout.setHorizontalGroup(
            jPanelSalirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelSalirLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButtonSalir, javax.swing.GroupLayout.DEFAULT_SIZE, 206, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanelSalirLayout.setVerticalGroup(
            jPanelSalirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelSalirLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButtonSalir, javax.swing.GroupLayout.DEFAULT_SIZE, 85, Short.MAX_VALUE)
                .addContainerGap())
        );

        getContentPane().add(jPanelSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(354, 124, -1, 97));

        jPanelSliders.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED));
        jPanelSliders.setLayout(new java.awt.GridBagLayout());

        jLabelVerde.setFont(new java.awt.Font("PMingLiU-ExtB", 1, 14)); // NOI18N
        jLabelVerde.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelVerde.setText("Verde");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.ipadx = 39;
        gridBagConstraints.ipady = 12;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(18, 2, 24, 34);
        jPanelSliders.add(jLabelVerde, gridBagConstraints);

        jLabelRojo1.setFont(new java.awt.Font("PMingLiU-ExtB", 1, 14)); // NOI18N
        jLabelRojo1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelRojo1.setText("Rojo");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.ipadx = 39;
        gridBagConstraints.ipady = 12;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(18, 4, 24, 36);
        jPanelSliders.add(jLabelRojo1, gridBagConstraints);

        jLabelAzul.setFont(new java.awt.Font("PMingLiU-ExtB", 1, 14)); // NOI18N
        jLabelAzul.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelAzul.setText("Azul");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.ipadx = 39;
        gridBagConstraints.ipady = 12;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(18, 5, 24, 37);
        jPanelSliders.add(jLabelAzul, gridBagConstraints);

        jSliderRojo.setMajorTickSpacing(15);
        jSliderRojo.setMaximum(255);
        jSliderRojo.setMinorTickSpacing(5);
        jSliderRojo.setPaintTicks(true);
        jSliderRojo.setValue(255);
        jSliderRojo.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jSliderRojoStateChanged(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 0;
        jPanelSliders.add(jSliderRojo, gridBagConstraints);

        jTextFieldRojo.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextFieldRojo.setText("255");
        jTextFieldRojo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldRojoActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.insets = new java.awt.Insets(0, 22, 0, 22);
        jPanelSliders.add(jTextFieldRojo, gridBagConstraints);

        jTextFieldVerde.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextFieldVerde.setText("102");
        jTextFieldVerde.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldVerdeActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 2;
        jPanelSliders.add(jTextFieldVerde, gridBagConstraints);

        jTextFieldAzul.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextFieldAzul.setText("255");
        jTextFieldAzul.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldAzulActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 4;
        jPanelSliders.add(jTextFieldAzul, gridBagConstraints);

        jSliderAzul.setMajorTickSpacing(15);
        jSliderAzul.setMaximum(255);
        jSliderAzul.setMinorTickSpacing(5);
        jSliderAzul.setPaintTicks(true);
        jSliderAzul.setValue(255);
        jSliderAzul.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jSliderAzulStateChanged(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 4;
        jPanelSliders.add(jSliderAzul, gridBagConstraints);

        jSliderVerde.setMajorTickSpacing(15);
        jSliderVerde.setMaximum(255);
        jSliderVerde.setMinorTickSpacing(5);
        jSliderVerde.setPaintTicks(true);
        jSliderVerde.setValue(102);
        jSliderVerde.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jSliderVerdeStateChanged(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 2;
        jPanelSliders.add(jSliderVerde, gridBagConstraints);

        getContentPane().add(jPanelSliders, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 227, 580, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jTextFieldAzulActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldAzulActionPerformed
        int numero = Integer.parseInt(jTextFieldAzul.getText());
        if ((numero > 255) || (numero < 0))
            showMessageDialog(null, "The value must be between 0 and 255.");
        jSliderAzul.setValue(Integer.parseInt(jTextFieldAzul.getText()));
    }//GEN-LAST:event_jTextFieldAzulActionPerformed

    private void jButtonSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSalirActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jButtonSalirActionPerformed

    private void jSliderRojoStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jSliderRojoStateChanged
        //Método que se llama cuando cambia el Slider
        jTextFieldRojo.setText(jSliderRojo.getValue() + "");
        cambiarColor();
    }//GEN-LAST:event_jSliderRojoStateChanged

    private void jSliderVerdeStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jSliderVerdeStateChanged
        //Método que se llama cuando cambia el Slider
        jTextFieldVerde.setText(jSliderVerde.getValue() + "");
        cambiarColor();
    }//GEN-LAST:event_jSliderVerdeStateChanged

    private void jSliderAzulStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jSliderAzulStateChanged
        //Método que se llama cuando cambia el Slider
        jTextFieldAzul.setText(jSliderAzul.getValue() + "");
        cambiarColor();
    }//GEN-LAST:event_jSliderAzulStateChanged

    private void jTextFieldRojoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldRojoActionPerformed
        int numero = Integer.parseInt(jTextFieldRojo.getText());
        if ((numero > 255) || (numero < 0))
            showMessageDialog(null, "The value must be between 0 and 255.");
        jSliderRojo.setValue(Integer.parseInt(jTextFieldRojo.getText()));
    }//GEN-LAST:event_jTextFieldRojoActionPerformed

    private void jTextFieldVerdeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldVerdeActionPerformed
        int numero = Integer.parseInt(jTextFieldVerde.getText());
        if ((numero > 255) || (numero < 0))
            showMessageDialog(null, "The value must be between 0 and 255.");
        jSliderVerde.setValue(Integer.parseInt(jTextFieldVerde.getText()));
    }//GEN-LAST:event_jTextFieldVerdeActionPerformed

    private void jRadioButtonTextoStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jRadioButtonTextoStateChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButtonTextoStateChanged

    private void jRadioButtonTextoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonTextoActionPerformed
        cambiarColor();
    }//GEN-LAST:event_jRadioButtonTextoActionPerformed

    private void jRadioButtonFondoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonFondoActionPerformed
        cambiarColor();
    }//GEN-LAST:event_jRadioButtonFondoActionPerformed

    private void jRadioButtonTextoFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jRadioButtonTextoFocusGained
        cambiarColor();
    }//GEN-LAST:event_jRadioButtonTextoFocusGained

    private void jRadioButtonFondoFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jRadioButtonFondoFocusGained
        cambiarColor();
    }//GEN-LAST:event_jRadioButtonFondoFocusGained

    private void cambiarColor () {
        //Primero obtenemos el color actual
        Color color = new Color (jSliderRojo.getValue(), jSliderVerde.getValue(), jSliderAzul.getValue());
        //Si está marcado el fondo, se cambia el fondo
        if (jRadioButtonFondo.isSelected()){
            jLabelTexto.setBackground(color);
        }
        if (!jRadioButtonFondo.isSelected()){
            jLabelTexto.setForeground(color);
        }
        
   
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Ventana().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup;
    private javax.swing.JButton jButtonSalir;
    private javax.swing.JLabel jLabelAzul;
    private javax.swing.JLabel jLabelRojo1;
    private javax.swing.JLabel jLabelTexto;
    private javax.swing.JLabel jLabelVerde;
    private javax.swing.JPanel jPanelRadioButtons;
    private javax.swing.JPanel jPanelSalir;
    private javax.swing.JPanel jPanelSliders;
    private javax.swing.JPanel jPanelTexto;
    private javax.swing.JRadioButton jRadioButtonFondo;
    private javax.swing.JRadioButton jRadioButtonTexto;
    private javax.swing.JSlider jSliderAzul;
    private javax.swing.JSlider jSliderRojo;
    private javax.swing.JSlider jSliderVerde;
    private javax.swing.JTextField jTextFieldAzul;
    private javax.swing.JTextField jTextFieldRojo;
    private javax.swing.JTextField jTextFieldVerde;
    // End of variables declaration//GEN-END:variables
}
